Hotel Cancelation Data Analysis Project - Muhammad Abrar

In [4]:
import sys
!python.exe -m pip install --upgrade pip

Requirement already satisfied: pip in c:\users\hp\pycharmprojects\pythonproject\pythonproject1\.venv\lib\site-packages (25.1.1)
Collecting pip
  Downloading pip-26.0.1-py3-none-any.whl.metadata (4.7 kB)
Downloading pip-26.0.1-py3-none-any.whl (1.8 MB)
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----------- ---------------------------- 0.5/1.8 MB 254.7 kB/s eta 0:00:05
   ----------- ---------------------------- 0.5/1.8 MB 254.7 kB/s eta 0:00:05
   ----------- ---------------------------- 0.5/1.8 MB 254.7 kB/s eta 0:00:05
   ----------- ---------------------------- 0.5/1.8 MB 254.7 kB/s eta 0:00:05
   ----------- ---------------------------- 0.5/1.8 MB 254.7 kB/s eta 0:00:05
   ----------------- ---------------------- 0.8/1.8 MB 248.1 kB/s eta 0:00:05
   ----------------- ---------------------- 0.8/1.8 MB 248.1 kB/s eta 0:00:05
   ----------------- ---------------------- 0.8/1.8 MB 248.1 kB/s eta 0:00:05
   ----------------- ---------------------- 0.8/1.8 MB 248.1 kB/s eta 0:00:05
   ----------------------- ---------------- 1.0/1.8 MB 257.9 kB/s eta 0:00:03
   ----------------------- ---------------- 1.0/1.8 MB 257.9 kB/s eta 0:00:03
   ----------------------- ---------------- 1.0/1.8 MB 257.9 kB/s eta 0:00:03
   ----------------------- ---------------- 1.0/1.8 MB 257.9 kB/s eta 0:00:03
   ----------------------- ---------------- 1.0/1.8 MB 257.9 kB/s eta 0:00:03
   ----------------------- ---------------- 1.0/1.8 MB 257.9 kB/s eta 0:00:03
   ----------------------------- ---------- 1.3/1.8 MB 248.8 kB/s eta 0:00:02
   ----------------------------- ---------- 1.3/1.8 MB 248.8 kB/s eta 0:00:02
   ----------------------------- ---------- 1.3/1.8 MB 248.8 kB/s eta 0:00:02
   ----------------------------------- ---- 1.6/1.8 MB 268.5 kB/s eta 0:00:01
   ----------------------------------- ---- 1.6/1.8 MB 268.5 kB/s eta 0:00:01
   ---------------------------------------- 1.8/1.8 MB 289.3 kB/s eta 0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 25.1.1
    Uninstalling pip-25.1.1:
      Successfully uninstalled pip-25.1.1
Successfully installed pip-26.0.1

In [5]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [7]:
df = pd.read_csv('C:/Users/hp/Downloads/ecommerce_dataset_5000.csv')

In [8]:
df.head(10)

  Row Labels Sum of Amount Count of Order ID Unnamed: 3
0        Jan         95849                40        NaN
1        Feb        100161                36        NaN
2        Mar         96757                37        NaN
3        Apr         97560                39        NaN
4        May         95827                35        NaN
5        Jun         96410                36        NaN
6        Jul         86240                29        NaN
7        Aug         92461                33        NaN
8        Sep         70662                31        NaN
9        Oct        100104                38        NaN

In [9]:
df.tail()

     Row Labels  Sum of Amount Count of Order ID Unnamed: 3
78          NaN            NaN               NaN        NaN
79          NaN            NaN               NaN        NaN
80   Row Labels  Sum of Amount               NaN        NaN
81          App        1069076               NaN        NaN
82  Grand Total        1069076               NaN        NaN

In [10]:
df.shape

(83, 4)

In [11]:
df.columns

Index(['Row Labels', 'Sum of Amount', 'Count of Order ID', 'Unnamed: 3'], dtype='str')

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 83 entries, 0 to 82
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Row Labels         40 non-null     str
 1   Sum of Amount      40 non-null     str
 2   Count of Order ID  19 non-null     str
 3   Unnamed: 3         6 non-null      str
dtypes: str(4)
memory usage: 2.7 KB

In [13]:
df.describe(include = 'object')

         Row Labels Sum of Amount Count of Order ID   Unnamed: 3
count            40            40                19            6
unique           31            32                15            6
top     Grand Total       1069076                36  Grand Total
freq              6             6                 2            1

In [14]:
for col in df.describe(include = 'object').columns:
    print(col)
    print(df[col].unique())
    print('*-'*40)

Row Labels
<StringArray>
[              'Jan',               'Feb',               'Mar',
               'Apr',               'May',               'Jun',
               'Jul',               'Aug',               'Sep',
               'Oct',               'Nov',               'Dec',
       'Grand Total',                 nan,        'Row Labels',
            'Female',              'Male',         'Cancelled',
         'Delivered',          'Returned',           'Shipped',
            'Bhopal',             'Delhi',            'Indore',
            'Jaipur',            'Mumbai', 'Count of Order ID',
             '18-25',             '26-35',             '36-50',
               '50+',               'App']
Length: 32, dtype: str
*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-
Sum of Amount
<StringArray>
[        '95849',        '100161',         '96757',         '97560',
         '95827',         '96410',         '86240',         '92461',
         '70662',        '100104',         '52323',         '84722',
       '1069076',             nan, 'Sum of Amount',        '610161',
        '458915',        '243743',        '258663',        '297336',
        '269334',        '231822',        '197273',        '242387',
        '189524',        '208070', 'Column Labels',        'Female',
            '39',            '47',            '93',            '54',
           '233']
Length: 33, dtype: str
*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-
Count of Order ID
<StringArray>
[  '40',   '36',   '37',   '39',   '35',   '29',   '33',   '31',   '38',
   '23',  '408',    nan, 'Male',   '56',   '43',  '175']
Length: 16, dtype: str
*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-
Unnamed: 3
<StringArray>
[nan, 'Grand Total', '76', '86', '149', '97', '408']
Length: 7, dtype: str
*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-

In [15]:
df.isnull().sum()

Row Labels           43
Sum of Amount        43
Count of Order ID    64
Unnamed: 3           77
dtype: int64

In [17]:
 df.describe()

         Row Labels Sum of Amount Count of Order ID   Unnamed: 3
count            40            40                19            6
unique           31            32                15            6
top     Grand Total       1069076                36  Grand Total
freq              6             6                 2            1